/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qicode_mylibrary_JniUtil */

#ifndef _Included_com_qicode_mylibrary_JniUtil
#define _Included_com_qicode_mylibrary_JniUtil
/*
 * Class:     com_qicode_mylibrary_JniUtil
 * Method:    getSecret
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qicode_mylibrary_JniUtil_getSecret
  (JNIEnv *env, jobject obj){
    return (*env)->NewStringUTF(env,"");
}
#endif
