/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include<com_qicode_mylibrary_JniUtil.h>
/* Header for class com_qicode_mylibrary_JniUtil */

//extern "C" {
/*
 * Class:     com_qicode_mylibrary_JniUtil
 * Method:    getSecret
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qicode_mylibrary_JniUtil_getSecret
  (JNIEnv *, jobject);
//}

